# Generated by Django 4.0.6 on 2022-07-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdetails',
            name='gender',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
